# Generated by Django 5.2.1 on 2025-06-09 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_transfer_flash_deals'),
        ('store', '0003_remove_flashdeal_one_product_type_only_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashdeal',
            name='reference_accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_flash_deals', to='store.accessory'),
        ),
        migrations.AlterField(
            model_name='flashdeal',
            name='reference_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_flash_deals', to='store.phonevariant'),
        ),
    ]
