# Generated by Django 5.2.1 on 2025-06-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_alter_flashdeal_reference_accessory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashdeal',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
