# Generated by Django 5.2.1 on 2025-06-08 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flash_deals', to='store.accessory')),
                ('phone_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flash_deals', to='store.phonevariant')),
            ],
            options={
                'verbose_name_plural': 'Flash Deals',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('accessory__isnull', True), ('phone_variant__isnull', False)), models.Q(('accessory__isnull', False), ('phone_variant__isnull', True)), _connector='OR'), name='one_product_type_only')],
            },
        ),
    ]
