# Generated by Django 5.2.1 on 2025-06-08 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_flashdeal'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='flashdeal',
            name='one_product_type_only',
        ),
        migrations.RemoveField(
            model_name='flashdeal',
            name='accessory',
        ),
        migrations.RemoveField(
            model_name='flashdeal',
            name='phone_variant',
        ),
        migrations.AddField(
            model_name='flashdeal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flash_deals/'),
        ),
        migrations.AddField(
            model_name='flashdeal',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashdeal',
            name='product_type',
            field=models.CharField(choices=[('phone', 'Phone'), ('accessory', 'Accessory')], default='phone', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashdeal',
            name='reference_accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_flash_deals', to='store.accessory'),
        ),
        migrations.AddField(
            model_name='flashdeal',
            name='reference_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_flash_deals', to='store.phonevariant'),
        ),
        migrations.AddField(
            model_name='flashdeal',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='flashdeal',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='flashdeal',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
