# Generated by Django 5.2.1 on 2025-06-09 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_flashdeal_one_product_type_only_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='flash_deal_end',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='is_flash_deal',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='phonevariant',
            name='flash_deal_end',
        ),
        migrations.RemoveField(
            model_name='phonevariant',
            name='is_flash_deal',
        ),
        migrations.RemoveField(
            model_name='phonevariant',
            name='sale_price',
        ),
        migrations.DeleteModel(
            name='FlashDeal',
        ),
    ]
